name: Check code is black formatted

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  black:
    name: Black format check

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install black
        python --version
        pip --version
        pip list
      shell: bash

    - name: Lint with black
      run: |
        black --check src
