name: Action on Initial commit

on:
  push:
    branches:
      - main

jobs:
  Initial-commit:
    name: Automatically set up repo on initial commit

    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, 'Initial commit')"

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Replace template README with project README
      run: |
        mv -f project-README.md README.md
      shell: bash

    - name: Find and replace REPO-NAME
      run: |
        NAME=${PWD##*/}
        sed -i "s/REPO-NAME/$NAME/g" README.md
      shell: bash

    - name: Self-destruct
      run: |
        rm .github/workflows/initial-commit.yml
      shell: bash

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      shell: bash

    - name: commit
      run: |
        git add .
        git commit -m "Auto workflow on initial commit"
        git push -u origin main
      shell: bash
