name: Initial pre-commit

on:
  push:
    branches:
      - main

jobs:
  README:
    name: pre-commit for initial commit

    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, 'Initial commit')"

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v2.0.3

    - name: Replace template README with project README
      run: |
        mv -f project-README.md README.md
      shell: bash

    - name: Find and replace REPO-NAME
      run: |
        NAME=${PWD##*/}
        sed -i "s/REPO-NAME/$NAME/g" README.md
      shell: bash

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      shell: bash

    - name: commit
      run: |
        git add .
        git commit -m "update README.md"
        git push -u origin main
      shell: bash
